sudo: false
language: node_js
node_js:
- stable
before_install:
- npm install -g gulp
install:
- travis_retry npm install
after_success:
- gulp coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- gulp build
deploy:
  - provider: npm
    email: j.andrichak@rackspace.com
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: nNyDVlg+R+Wc94MO2GBZJayMhUGR7smcM7gh5bfkSitJSS9mPm9Or5F18fYgWKSY5c4u2u5Mx+qAeAEN301izYd6qgBc78Nkhtd8NdQAzvamzAY8LgKzCrhyra2Ac7pq6Sw+/0rvGiLk5P9h1m555wSKuljh33V8UhanXYxL54o=
